### PR TITLE
RFC: message factory

### PR DESCRIPTION
**Pull request by mtymek**
Hi Aaron,

When thinking what's the best way to implement PSR-7 compatible messages, I realized that once `Stream` is implemented, we can actually reuse existing PSR-7 library. See how this PR looks like - what do you think?

### CODE REVIEW

**Comment by trowski** [comment]
I'm not a fan of static factory classes, I usually prefer creating an instance of a factory and having methods on that object. This way someone can make a slightly different factory by overloading a method, rather than starting from scratch. Also a `MessageFactoryInterface` could be added as well. Basically it would be exactly what you have, minus `static` on the methods.

See `ServerFactory` and `ServerFactoryInterface` here: https://github.com/icicleio/Icicle/tree/master/src/Socket/Server

What are your thoughts?

**Comment by mtymek** [comment]
I don't have any preference between static and non-static methods in this case.

Do you see any use case for overloading factory, or for an interface? For me it is just an utility class, with single purpose: feed it with Icicle's message, get 1:1 mapping as PSR-7 message. What could be extended there?

We could also make methods non-static, but declare this class as `final` - no extension now, but if someone finds good use case, we can allow it without BC break.

**Comment by trowski** [comment]
If you don't have a preference, I'd rather a non-static factory then. I'm not sure I'd add `final` though, why limit it for no reason?

I wonder if there was a way we could avoid dependency on a specific PSR-7 implementation. If someone wants to use PSR-7 messages, they probably have a dependency on a PSR-7 implementation, and now the bridge would potentially be adding another. That's part of the reason I was thinking of having a factory interface.

**Comment by mtymek** [comment]
It's actually something new for me - I'm inspired by this article: http://ocramius.github.io/blog/when-to-declare-classes-final/.
Basically, bridge should take an interface and return class implementing another one. 
Returning something else (for instance concrete `Request` class with additional methods) would be dangerous - it would allow breaking the contract. Making class `final` prevents users from doing so.
Still, if someone finds another reason that makes sense, we can remove `final` class without BC break.

Avoiding dependency would be difficult and likely hackish - specification doesn't tell anything about constructors (which is actually good for flexibility). Anyway, `MessageFactory`'s contract promises to return `RequestInterface` or `ResponseInterface`, so all should be fine from OOP perspective.

See update I just pushed.

**Comment by trowski** [comment]
That article was interesting and had some good points. I've been writing a lot of library code that users might want to extend. In this case I think you're right, there isn't much reason to extend the class, instead it should just be encapsulated if a user wants to change some behavior. Otherwise with the interface they could also just write a different factory that returned some other PSR-7 implementation's messages.

This is shaping up to be simpler than I thought. What else is missing? In what contexts would someone use this? Would they want to convert back to an Icicle compatible message or stream?

**Comment by mtymek** [comment]
Glad you agree, means I understood that article correctly ;)
Indeed, next step would be to create methods for converting PSR7 messages back to Icicle's. With this, we will be able to connect Icicle to any middleware framework, like Slim3 or Harmony. 
Any suggestions on coverting PSR streams back?
This implementation still not perfect (for instance requestTarget is not passed), but I will clarify it later, after seeing full stack in action.

**Pull request merged**
