### PR TITLE
More StreamInterface functions

### PR DESCRIPTION
**Pull request by mtymek**
I'm getting back with more methods of `StreamInterface`. I'm a bit unsure with what to do with remaining ones. `eof`: does it make any sense for socket streams? `getContents` and `toString` could be implemented using `while ($this->stream->isReadable())`, but does it make sense at all?

### CODE REVIEW

**Comment by trowski** [comment]
~~Can you rebase on the commits I added after your last PR? Then also update the loop that manually ticks the event loop to be like what I implemented in `read()` and `write()`.~~ Nevermind, there weren't any conflicts so I just went ahead and merged.

PHP uses `feof()` to indicate that a stream socket has closed, so `eof()` does make sense on socket streams. In the future Icicle will use the same interfaces for file streams and IPC streams, so a stream could be a number of things.

Is `Psr\Http\Message\StreamInterface::isReadable()` suppose to return `true` only if the stream is still readable, or just if the stream was a readable stream type? Same with `Psr\Http\Message\StreamInterface::isWritable()`. I'm not entirely clear on that since `eof()` really only makes sense for readable streams, but then how to do you tell if a writable-only stream has closed?

I believe `eof()` should just be `return $this->isReadable() && $this->stream->isReadable();`. If `eof()` needs to also report something for writable only streams it would be slightly more complicated than that.`getContents()` can just do reads looping on `eof()`, using `getContents()` in `__toString()` catching `RuntimeException`.

**Comment by trowski** [comment]
I merged in your changes and implemented the remaining stream methods as described above. You'll definitely want to rebase or just make another fork for the next PR. Let me know if you think my code makes sense or not.

**Comment by mtymek** [comment]
`eof` should be true when stream is not readable anymore, right?

``` php
return !$this->isReadable() || !$this->stream->isReadable();
```

I read some docs, and didn't find any good answer on how `eof()` should work for socket streams in write context. My gut says that what you proposed is alright from logic standpoint ("eof" = everything is read, so readable stream is not readable anymore).

BTW, why did you change `Prophecy` mocks to old PHPUnit's engine? If you are not familiar with Prophecy, I strongly encourage you to learn it - surely you will not want to go back! :)

I wrote a few more tests (unfortunately I don't have time to finish full suite today), I will create separate PR with them.

**Comment by trowski** [comment]
Err.... yeah, `eof()` should be what you wrote. I was thinking about it the opposite way for some reason.

I mentioned in https://github.com/icicleio/Psr7Bridge/pull/1#issuecomment-110153632 as to why I changed those tests back to PHPUnit's old mocks. It's on my todo list to figure out why Prophecy broke those tests. Prophecy otherwise looks very nice and I will be using it in the future.

**Pull request merged**
